### ISSUE TITLE
Doesn't work with linum-mode

### ISSUE THREAD

**Issue by hyperair** [joostkremers/visual-fill-column#17]
It initially re-renders everything according to fill-column, but the moment you move to the next line, linum redraws everything in its original state.

**Comment by joostkremers** [comment]
Yes, this is a known problem and one that is essentially unfixable, because `linum-mode` is far too aggressive about using the margins.

As an alternative, you can use `nlinum-mode` (available from ELPA). There are still some (equally unfixable) incompatibilities between `nlinum-mode` and `visual-fill-column-mode`, but the basic functionality works and any problems with the display can be fixed by rerendering the window (e.g., by switching to another buffer and back again).

I had a long discussion about this on the emacs-devel mailing list, because the way Emacs works right now, it's impossible for two packages to use the margins in a way that does not cause them to interfere with each other. But the changes needed to fix this are complex, so it was decided not to do anything about it for the moment.

**Comment by svend** [comment]
visual-fill-column works with Emacs 26 new native line numbers. According to the NEWS entry, the other line number packages will be considered obsolete.

> Linum mode and all similar packages are henceforth becoming obsolete.
> Users and developers are encouraged to switch to this new feature
> instead.

**Comment by joostkremers** [comment]
Thanks for the report. I was hoping the new native line numbers wouldn't pose a problem anymore for `visual-fill-column`, but I hadn't had time to test yet.
