### ISSUE TITLE
Does not respond to font changes

### ISSUE THREAD

**Issue by purcell** [joostkremers/visual-fill-column#2]
Hi Joost! I noticed when using `writeroom-mode` that when the global font size is made bigger, the column of text actually gets narrower. I suspect this is due to `visual-fill-column`.

To try this out conveniently, install my `default-text-scale` package and try bumping up the font size in a writeroom buffer.

Note that `after-setting-font-hook` is generally run when the default font size changes in a frame.

Any ideas what's going on here? Calling `visual-fill-column--adjust-window` explicitly doesn't seem to help.

**Comment by joostkremers** [comment]
Hi, thanks for reporting this. I tried it out and can confirm the problem. After the font size change, the margins should be recomputed, but they're not, because they are only recomputed upon a window change, which a font change isn't. So you end up with margins that are way too wide for the font size.

What surprises me is that calling `visual-fill-column--adjust-window` doesn't fix the issue. I noted that if I do `C-x 3` to split the window horizontally and then `C-x 1` to get rid of the extra window again, the margin is adjusted correctly.

Adding `visual-fill-column--adjust-window` to `after-setting-font-hook

**Comment by purcell** [comment]
Yeah, that's exactly what I was trying, before I gave up. :-)

**Comment by purcell** [comment]
P.S. `writeroom-mode` has been extremely useful for me recently. Thank you.

**Comment by joostkremers** [comment]
Glad that `writeroom-mode

**Comment by joostkremers** [comment]
BTW, adding `visual-fill-column--adjust-window` to `after-setting-font-hook

**Comment by purcell** [comment]
> After changing the font size, the total window width as returned by the function window-total-width is not correct. Although the font size change means there are more/fewer characters on a line, the total window width is still at the old value. This doesn't get fixed until the window is split horizontally.
> 
> I can reproduce the problem with emacs -Q, so I'd say this qualifies as an Emacs bug. I'll report it and see what the experts say.

Yep, I think you're right.

**Comment by joostkremers** [comment]
The report is here:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19972

Note that we seem to have missed one thing: when doing a font size change, the size of the frame is normally adjusted. If I understand your code correctly, you’re doing some stuff in `default-text-scale.el` to compensate for that, right?

**Comment by purcell** [comment]
> Note that we seem to have missed one thing: when doing a font size change, the size of the frame is normally adjusted. If I understand your code correctly, you’re doing some stuff in default-text-scale.el to compensate for that, right?

Yes, but that's not actually relevant to the bug, I'd say:

- Consider the case of full-screen frames, which never change in pixel size. The window-width should change when the font size changes in this case too.
- `set-frame-font` is a built-in function with a `KEEP-SIZE` param which tells it to try to preserve the pixel-size of the frame after the font has changed: my code is copied from there.

So the width should really get recalculated in any case.

**Comment by purcell** [comment]
I'll email the above to the bug address so that I can be involved in the discussion.

**Comment by joostkremers** [comment]
> Yes, but that's not actually relevant to the bug, I'd say:

Yeah, I figured that out after posting. The discussion on the bug tracker is now focussing on the case when the window is maximised.

**Comment by joostkremers** [comment]
The relevant bug has been squashed now. The fix will appear in Emacs 25, so (unfortunately) it won't be included in 24.5.

**Comment by purcell** [comment]
Ah. Is it fixed on OS X too? I had the impression from the bug discussion that attention had wandered away from the actual problem. :-)

**Comment by joostkremers** [comment]
Well, the problem you reported resulted from `window-total-width` returning the wrong window width after the font change. I didn’t understand the discussion why, but the fix introduced in the master branch fixed the problem, in that `window-total-width` started returning the correct width.

Since I could confirm the problem on my Linux machine, I just assumed you were talking about Linux as well. Since I don’t have an OS X machine, I cannot determine whether it was fixed there as well. You’d have to compile the Emacs master branch yourself to find out…

BTW, the latest version of `visual-fill-column-mode` doesn't use `window-total-width` any more, so the problem should be fixed anyway.

**Comment by purcell** [comment]
> Since I don’t have an OS X machine, I cannot determine whether it was fixed there as well. You’d have to compile the Emacs master branch yourself to find out…

I'll give that a go, because I'm curious. :-)

> BTW, the latest version of visual-fill-column-mode doesn't use window-total-width any more, so the problem should be fixed anyway.

Nice!

**Comment by purcell** [comment]
Re. `window-total-width`, I was getting wrong behaviour even with `window-width`: it returned the same number after scaling the `default` face.
