### ISSUE TITLE
Strange margins after Magit commits

### ISSUE THREAD

**Issue by lunaryorn** [joostkremers/visual-fill-column#22]
Follow up from the discussion in https://github.com/lunaryorn/.emacs.d/commit/cbf342fd0dbf95dcad02d5b6a5941f567e4bb07b.

/cc @joostkremers @tarsius @manuel-uberti

**Comment by joostkremers** [comment]
The problem seems to be that the window margins of the Magit status buffer are set **before** the `COMMIT_EDITMSG` is displayed in that window. You can determine this by doing the following (also works in `emacs -Q` with Magit and its dependencies loaded):

``` emacs-lisp
(defun my-set-wm ()
  (message "my-set-wm on %s / %s" (selected-window) (get-buffer-window))
  (set-window-margins (selected-window) 5 5))

(add-hook 'text-mode-hook 'my-set-wm)
```

Then modify some git-controlled file, run `magit-status`, stage the file and initiate the commit.

At this point, you'll note that even though the `COMMIT_EDITMSG` buffer is in `text-mode`, its margins are not set. This does not mean that `text-mode-hook` wasn't run, however. It was, but for some reason (that I'm not clear about) its effect was undone once the `COMMIT_EDITMSG` buffer was shown.

If you now view the `*Messages*` buffer, you'll notice the following:

    my-set-wm on *magit: temp / nil [2 times]

That is, at the point `text-mode-hook` is run, `(selected-window)` returns the window displaying the `*magit: temp` buffer (i.e., the Magit status buffer). This is the right window, since it's the window that is going to display the `COMMIT_EDITMSG` buffer in a second, but right now, it's not displaying it yet.

Now, all of this wouldn't be a problem that anyone would notice, **if** `with-editor-return` (the function that actually kills the `COMMIT_EDITMSG` buffer) wouldn't restore the window configuration that existed before `COMMIT_EDITMSG` is displayed. In fact, I edebugged `with-editor-return` and one can see the `*magit: temp` buffer **without** margins at the point where `with-editor-return` calls `(server-done)`, with the margins suddenly appearing when `set-window-configuration` is called with the previous window config.

I'm not sure how to fix the problem, but I will keep looking.

**Comment by lunaryorn** [comment]
@joostkremers Could you push a new tag with this fix?  I'm installing from MELPA Stable :blush:

**Comment by joostkremers** [comment]
The message everyone's been waiting for. Apologies for my verbosity, I just needed to think out loud on this one... :worried:

Anyway, on a high level, the problem was that `v-f-c-mode` wasn't careful enough about which windows it was adjusting the margins of. This mostly works fine, because before a buffer is displayed in a window, the window's margins are normally unset, and `v-f-c-mode` uses the buffer-local part of `window-configuration-change-hook` to set them again. Because I use the buffer-local part of that hook, I assumed that only buffers in which `v-f-c-mode` is activated would have their window margins set.

Turns out that assumption is not entirely correct. It seems that the buffer-local part of `window-configuration-change-hook` is also run on a window *before* it changes its buffer, but with the *new* buffer already current.

This isn't a problem most of the time, because the old buffer is being switched away from and when it's displayed again later, its window will first have its margins unset. But by saving a window configuration and restoring it later, it's apparently possible to get around this.

I've fixed the code so that only windows whose buffers have  `v-f-c-mode` enabled have their margins adjusted. This means that when the `COMMIT_EDITMSG` buffer is popped up, the margins are set only *after* the buffer becomes visible, not (also) before it.

:sweat_smile:

**Comment by joostkremers** [comment]
> Could you push a new tag with this fix? I'm installing from MELPA Stable :blush:

Done. (Thanks for the reminder, this is a bug fix so IMHO it **should** have a new tag.)

**Comment by manuel-uberti** [comment]
Fantastic, thank you!

**Comment by lunaryorn** [comment]
@joostkremers You're the best; thanks so much for fixing this… I don't dare to imagine the horrors of Emacs internals you must have seen while debugging this :wink:
