### ISSUE TITLE
(global-visual-fill-column-mode 1) doesn't work in .emacs, just when executed

### ISSUE THREAD

**Issue by LindyBalboa** [joostkremers/visual-fill-column#27]
Running latest emacs from Github. I have the following block in my .emacs. I have tried rearranging the commands to no effect. But as soon as I call it from M-x or C-x-C-e it, it works. Any thoughts? Thanks.

```
(global-display-line-numbers-mode t)
(setq display-line-numbers-type 'visual)

(global-visual-line-mode 1)
(use-package visual-fill-column
  :config
  (setq visual-fill-column-width 80)
  (setq visual-line-fringe-indicators '(nil right-curly-arrow))
  (global-visual-fill-column-mode 1)
  )
```

**Comment by joostkremers** [comment]
I suspect you'll need to put the call `(global-visual-fill-column-mode 1)` in an `:init` clause, not in a `:config` clause. The `:config` clause is executed when the package is loaded, but that never happens in your setup, because it's the call to `global-visual-fill-column-mode` that should cause it to load. The `:init` clause is executed when Emacs is started up, so that should work.

Note that I haven't tested `visual-fill-column` on Emacs 26 yet, so I'd be interested in hearing if any problems turn up. Esp. regarding the new native line numbers.

**Comment by noctuid** [comment]
@joostkremers I've been using native line numbers since they first hit master and always use visual-fill-column for org mode, which I use daily. I haven't noticed any problems specifically related to visual-fill-column but will make an issue if I do (I found an issue with another package due to wrapped lines; visual-fill-column isn't the cause but just makes the problem more obvious since it results in more line wrapping).

**Comment by joostkremers** [comment]
@noctuid Thanks for the info, good to know there doesn't seem to be any breakage!

**Comment by LindyBalboa** [comment]
Yea, seems this voyager from the land of vim still has a thing or two to learn about emacs/elisp.

I switched this and it at least seems to be loading properly.
```
(add-hook 'after-init-hook 'global-visual-line-mode)
(use-package visual-fill-column
  :init
  (global-visual-fill-column-mode)
  :config
  (setq visual-line-fringe-indicators '(nil right-curly-arrow))
  (setq visual-fill-column-width 100))
```
