### ISSUE TITLE
In right-to-left buffers the right margin is expanded

### ISSUE THREAD

**Issue by tareefdev** [joostkremers/visual-fill-column#28]
So the text appears at the window’s left side as following

![screenshot from 2017-12-03 11-18-18](https://user-images.githubusercontent.com/17391433/33523623-b12052ee-d81c-11e7-922b-9bca489059a5.png)

emacs 25.3.1, I use these configuration in my init file:

```
(global-visual-line-mode 1)
(global-visual-fill-column-mode)
(setq-default fill-column 80)
```

**Comment by joostkremers** [comment]
`visual-fill-column-mode` should honour the value of `bidi-paragraph-direction`, so if you set that variable to `t` in your Arabic buffers, it should work.

I am open to suggestions on improving `visual-fill-column-mode`'s treatment of RTL text, by the way. Perhaps there should be a dedicated, buffer-local variable for it.

**Comment by tareefdev** [comment]
I thought since emacs shows my Arabic content from right-to-left direction so the `bidi-paragraph-direction`'s value is set to `t`.

I read the following from [Bidirectional Editing](https://www.gnu.org/software/emacs/manual/html_node/emacs/Bidirectional-Editing.html):

>  Emacs determines the base direction of each paragraph dynamically, based on the text at the beginning of the paragraph. However, sometimes a buffer may need to force a certain base direction for its paragraphs. The variable bidi-paragraph-direction, if non-nil, disables the dynamic determination of the base direction, and instead forces all paragraphs in the buffer to have the direction specified by its buffer-local value. The value can be either right-to-left or left-to-right. Any other value is interpreted as nil. 

So I guess emacs looks to the beginning of the paragraph and set the direction to RTL?

I am a newbie in emacs, I searched in the internet about how to set the value of `bidi-paragraph-direction` to `t` manually but I didn't find anything, could you just help me?

thanks

**Comment by joostkremers** [comment]
> So I guess emacs looks to the beginning of the paragraph and set the direction to RTL?

More precisely, Emacs looks at the first directional character in the paragraph. Letters are directional, but punctuation usually is not. But in essence, yes, Emacs looks at the paragraph and determines the bidi direction from there.

The problem is that Emacs does this for each paragraph separately, so if you mix say English and Arabic text, the paragraphs in Arabic will show RTL, the ones in English LTR.

This is, unfortunately, something that `visual-fill-column-mode` cannot handle. If the text direction can change with every paragraph, there's no good way to determine whether the text should be at the left or right of the window.

> I am a newbie in emacs, I searched in the internet about how to set the value of bidi-paragraph-direction to t manually but I didn't find anything, could you just help me?

`bidi-paragraph-direction` is a buffer-local variable, which means that you cannot set it for all of Emacs. (Since much of Emacs is hard-coded in English, that wouldn't be a very good idea in any case.) Instead, you can only set it for one buffer at a time. To do that, you can type:

    M-: (setq bidi-paragraph-direction 'right-to-left)

Note the quote (`'`) sign before `right-to-left`.

You will have to do this each time you open a text file in Arabic, so it's not very practical. For a more permanent solution, do:

    M-x add-file-local-variable RET

Then at the prompt, type:

    bidi-paragraph-direction RET

followed by:

    right-to-left RET

(where `RET`means to press the `RETURN` key, but you probably figured that out. :smiley:)

This will add some lines to the end of your file. That's not ideal either, but they're marked as comments, so they won't show up if you convert the text to html or something else. The advantage is that the next time you open the file, the paragraph direction is set.

You'll have to do this for each file in Arabic that you have, but only once for each file. You just need to make sure you keep the text that is added at the bottom of the file.

Read more here:

https://www.gnu.org/software/emacs/manual/html_node/emacs/File-Variables.html#File-Variables 

and here:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer_002dLocal-Variables.html#Buffer_002dLocal-Variables

The latter is the manual for Lisp programmers, so it may contain more info than you need. :smiley:

**Comment by joostkremers** [comment]
BTW, as an alternative, you could set `visual-fill-column-center-text` to `t`. That puts the text in the centre of the window, which avoids having to set `bidi-paragraph-direction`.

`visual-fill-column-center-text` is a user option, so you can set it through Customize (`M-x customize-option RET visual-fill-column-center-text RET`).

**Comment by tareefdev** [comment]
Thank you very much for this detailed information 😊
But there are still two problems:

- Even I added the following lines to my init file:

    (global-visual-line-mode 1)
    (global-visual-fill-column-mode)
    (setq-default fill-column 80)

I still need to do:

`M-x visual-fill-column-mode RET`

to activate visual-fill-column mode!

- The second one, after I activated visual-fill-column mode in **Arabic buffers**, and then I moved to line up or down the lines will re-wrapping at the the window edge! so I need to resize emacs window to re-wrapping lines again to fill column and so on!

**Comment by joostkremers** [comment]
Sorry for the late reply. I don't really know what's going on in your case. The lines in your init file should work... The rewrapping effect you describe is even stranger. :confused:

Do you think you could send me an Arabic text file, so I can do some experimenting myself?

**Comment by tareefdev** [comment]
> Sorry for the late reply.
It's OK, It's not a matter of urgency.

> Do you think you could send me an Arabic text file
It sounds good, here is an Arabic text
[فيرفكس عاد.zip](https://github.com/joostkremers/visual-fill-column/files/1584099/default.zip)


thank you for your interest

**Comment by tareefdev** [comment]
Hi @joostkremers sorry to bother you again about this, did you test the Arabic text in your emacs?

**Comment by joostkremers** [comment]
Hi, I opened your file in Emacs, but i can't see anything weird happening. What version of Emacs are you using, and what OS do you use?

**Comment by tareefdev** [comment]
Hey, I run Emacs 26.1 on Arch Linux, could you please take a screenshot for that text in your emacs.

**Comment by joostkremers** [comment]
This is when loading the file:

![screenshot from 2018-10-24 11-55-16](https://user-images.githubusercontent.com/191630/47423070-7269ee80-d784-11e8-85ea-6690bffa71c7.png)

(In my setup, `visual-line-mode` and `visual-fill-column-mode` are activated automatically for `.md` files.)

And this is after adding the file-local variable `bidi-paragraph-direction` to the file (and reopening it):

![screenshot from 2018-10-24 11-56-49](https://user-images.githubusercontent.com/191630/47423145-9cbbac00-d784-11e8-80b7-46e32e8a5ccc.png)

Moving point doesn't cause any strange rewrapping or anything...

**Comment by tareefdev** [comment]
When I opened this issue I was using Emacs 25, and for some reason setting `bidi-paragraph-direction` to `RTL` didn't work. 

I tried this again with Emacs 26.1, and it works! Also, I can confirm that moving the point doesn't rewrap the selected line.

Thanks so much for your follow-up and attention here, and for informative answers. Have a good day.
