### ISSUE TITLE
nov-mode, justify-knuth/plass, and visual-fill-column

### ISSUE THREAD

**Issue by emacsomancer** [joostkremers/visual-fill-column#29]
I've been trying out [nov-mode](https://github.com/wasamasa/nov.el), an epub-reader for emacs. In the README, the nov-mode author provides a demonstration of using some functions from [justify-kp](https://github.com/Fuco1/justify-kp), paragraph justification for emacs using the Knuth/Plass algorithm. 

While I can get the nov-mode author's example of using justify-kp to work, I haven't managed to figure out how it can be made compatible with visual-fill-column mode.  Do you have any insights?  It would be great to be able to properly use emacs to read epub with real paragraph justification.

**Comment by joostkremers** [comment]
TBH I'm not entirely sure what you mean by making `justify-kp` "compatible" with `v-f-c-mode`, but a quick look at `nov-mode` and `justify-kp` suggests to me that if you use the latter, you shouldn't be using `v-f-c-mode` at all. `v-f-c-mode` makes sense if Emacs handles text wrapping, while `justify-kp`'s goal is to take text wrapping away from Emacs.

For example, from the relevant (second) screen shot on the `nov-mode` page, I gather that `justify-kp` occasionally places text beyond the margin (cf. the word `'window'` in the quote at the top), but because `v-f-c-mode` narrows the text area, this is not possible. Emacs would simply put `'window'` on the next line, regardless of what `justify-kp` does.

IOW `justify-kp` needs a wide text area, `v-f-c-mode` narrows it.
