### ISSUE TITLE
Org-mode: unexpected new lines

### ISSUE THREAD

**Issue by manuel-uberti** [joostkremers/visual-fill-column#3]
I am getting some weird behavior in ```org-mode```.
This is the text I have typed:
```
In the years before 1965, Coltrane was already working on his own sound. His
playing was highly influenced by Miles Davis modal solutions. Using these 
ideas
for his saxophone was only a part of a greater plan Coltrane had in mind.
```
As you can see, something happened after ```ideas```. If I disable ```visual-fill-column```, I get this:
```
In the years before 1965, Coltrane was already working on his own sound. His
playing was highly influenced by Miles Davis modal solutions. Using these ideas
for his saxophone was only a part of a greater plan Coltrane had in mind.
```
Which is correct. My ```fill-column``` is set to 80, and the second line in that text is only 79 characters.

**Comment by joostkremers** [comment]
What Emacs version are you using? I don't seem to be able to replicate the problem.

Emacs' wrapping algorithm isn't perfect, I suspect you're running into one of the imperfections. For some reason, the algorithm determines that `ideas` needs to be wrapped, even though there would be enough room for it. Since you're text contains hard newlines and there is one after `ideas`, it ends up on a line of its own.

I'm not sure there's anything `visual-fill-column-mode` can do about it, but if I manage to replicate the problem, I'll see if I can find out a bit more about it.

**Comment by manuel-uberti** [comment]
I'm using version ```25.0.50.1```.

**Comment by joostkremers** [comment]
I took a closer look and realised that it is a problem with `visual-fill-column-mode`. Should be fixed now.

BTW, I suspect the difference between `org-mode` and `AUCTeX` is that you don't have `visual-line-wrap` activated in LaTeX buffers.

**Comment by manuel-uberti** [comment]
It is fixed now, thank you.
And you were right about ```AUCTeX```, but turning on ```visual-line-mode``` and ```visual-fill-column``` works here as well. So thanks again.
