### ISSUE TITLE
Emacs freeze with visual-fill-column and display-line-numbers-mode

### ISSUE THREAD

**Issue by tareefdev** [joostkremers/visual-fill-column#30]
Emacs 26.1 has a new option called `display-line-numbers-mode` which is instead of `linum-mode`, but if I activated `visual-fill-column` which this new option emacs totally freezed.

**Comment by joostkremers** [comment]
What OS are you using? GUI Emacs or CLI? I'm on Linux, with a GUI Emacs, and I don't seem to have  problem using `display-line-number-mode` together with `visual-fill-column-mode`.

I only did a quick test, though, because I normally don't use the two together. (I use both, but not in the same buffers).

Does it occur with `emacs -Q` as well, after loading `visual-fill-column.el`?

**Comment by tareefdev** [comment]
Let me be more accurate, when I activate `display-line-numbers-mode` (I have `visual-fill-column` active by default for all buffers) and **then** change the window size emacs froze totally and I have to kill it. 

I tried to comment the  `visual-fill-column` package out in my init file, and emacs didn't freeze when changing the window size, even with `display-line-numbers-mode`, so I assumed the problem is with `visual-fill-column`.

BUT, I made another test right now with `emacs -q`, I activated the display line mode, load visual fill column package and activated it, changed the window size, but emacs didn't freeze! hmmm

So I'm not sure how to determine the problem

**Comment by joostkremers** [comment]
Well, the only way I can think of is to selectively comment out parts of your init file until you find the line or lines that cause the problem. You'll probably need to keep `visual-fill-column` activated, because it seems to be part of the problem.

If you do find something, let me know, perhaps I can help find out what exactly the cause of the problem is.

**Comment by tareefdev** [comment]
The issue was in my GPU driver; I faced other freezing with other programs. After solving the Intel's driver problem, the two options work fine together now.

Thanks always for your helping.
