### ISSUE TITLE
Error during redisplay

### ISSUE THREAD

**Issue by manuel-uberti** [joostkremers/visual-fill-column#36]
Hi,

I am using latest `visual-fill-column` from MELPA, and I get this in `*Messages*` every time I switch buffer with <kbd>C-x b</kbd>:

```
Error during redisplay: (visual-fill-column--adjust-frame #<window 20 on *scratch*>) signaled (error "Window is on a different frame")
```

A quick recipe to reproduce the error:

- `emacs -Q`
- <kbd>M-x package-initialize</kbd>
- <kbd>M-x visual-fill-column-mode</kbd>
- <kbd>C-x b</kbd>
- <kbd>RET</kbd>

These are some info on my system, in case you need them:

```
GNU Emacs 27.0.50 (build 14, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-01-26

Repository revision: 4eb78a47e0be59c6d7b886cfe82ce56b276a52bd
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 9 minutes, 19 seconds
Default font: Source Code Pro
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.1 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

If you need me to provide further details, feel free to ask.

**Comment by joostkremers** [comment]
Could you try the same with `debug-on-error` set to `t` and then post the backtrace?

I'm using Emacs 26, it's perfectly possible that something changed recently that causes this issue.

**Comment by joostkremers** [comment]
Since your Emacs was built on Jan. 26, I assume you update it regularly? Were you running 27 before last Saturday as well? If so, do you happen to know when you previously updated it?

The error seems to be triggered by `window-list`, which is a C function, and which hasn't changed between Emacs 26 and Emacs 27. From what I can tell, if you pass it a frame (which I'm doing in the relevant function), it takes the selected window on that frame, passes it to a function `CHECK_WINDOW` and then checks if the window's frame is equal to the original frame. Which it should be, but for some reason it isn't.

This looks like something I'll need to ask about on emacs-devel. It could be that some recent changes to `window.c` introduced a bug, or (more likely) I'm using `window-size-change-functions` in a way that is not correct...

**Comment by manuel-uberti** [comment]
I update Emacs on a daily base, and it wasn't happening before Saturday.

**Comment by manuel-uberti** [comment]
Hi, no worries at all. :)

The message is still there using this version of Emacs trunk:
```
Repository revision: 713eece307bf48717b868f21789eed8160ada5ba
```

**Comment by joostkremers** [comment]
It's a feature, not a bug... :confused:

It seems that the use of `window-size-change-functions` has changed recently, at least judging by its doc string. `v-f-c-mode` uses this hook to keep track of window size changes. It adds a function to this hook that adjusts a window's margins so that a window size change doesn't result in the buffer text suddenly becoming too narrow or too wide.

But the function was added to the local part of the hook, which worked fine before, but after (apparently) a recent change, the local part of `window-size-change-function` is passed the **window** as an argument, not the frame.

It seems the easiest fix is to remove the `'local` argument from the second `add-hook`call in `visual-fill-column-mode--enable`:

    (add-hook 'window-size-change-functions #'visual-fill-column--adjust-frame 'append 'local)

should become:

    (add-hook 'window-size-change-functions #'visual-fill-column--adjust-frame 'append)

At least that doesn't cause any trouble on Emacs 26.

But I also noticed that Emacs 27 will have three more hooks that are run when window/buffer configurations change, so I'm not sure if this is the only fix that's needed for Emacs 27, or if more (or better) fixes are going to be required.

Let me know if that fix solves the problem. If you run into any more trouble, I'd appreciate a heads-up as well.

**Comment by manuel-uberti** [comment]
Sure. Are you going to push the change, or do you want to clone the repo and see if it works for me locally before changing your package for everybody?

**Comment by joostkremers** [comment]
> [...]  or do you want me to clone the repo and see if it works for me locally before changing your package for everybody?

Yes, I was hoping you'd be so kind. :smiley:

> Ok, I cloned it locally and tried your suggestion. The message is gone now. Thank you!

Thanks for letting me know! I'll push the change to Github so you won't need to run off a cloned repo.

**Comment by manuel-uberti** [comment]
Fantastic, thanks for the support!
