### ISSUE TITLE
Still having issues in Emacs 26.1 (either doesn't work, or it hangs)

### ISSUE THREAD

**Issue by TRSx80** [joostkremers/visual-fill-column#44]
Hello Joost,

First off, thank you for sharing visual-fill-column!  :beers:

It is exactly what I have been looking for, for literally years.  I was so excited about it initially that I actually contributed my very [first](https://www.emacswiki.org/emacs/VisualFillColumn) [edits](https://www.emacswiki.org/emacs/LineWrap) to EmacsWiki to let others know about it.

Now, if I could only get it to work.  :smile: :smile: :smile:

I am not sure what the common thread here is (yet), I am still investigating.  After reading several other (seemingly related) issues, I decided to just keep these together, at least for the time being.  From what I read, these issues  were supposed to be fixed in Emacs 26.1, and yet I still seem to be experiencing them.

### Environment

Executing <kbd>M-x</kbd> `emacs-version` <kbd>return</kbd> yields:
`GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-08, modified by Debian`

In case it matters, I am using `i3-gaps` as window manager, on top of a vanilla Debian Bullseye XFCE install.  I am happy to further report back any other information you feel might be relevant.

### Symptom 1: global-visual-line-mode not working

By not working, I mean that the mode seems to be enabled, it is just not doing anything (not wrapping any text).  I enable it like so in my init file:
```
(global-visual-line-mode 1)
(setq-default visual-fill-column-width 103)
```
I can go into buffer in question, and execute <kbd>C-h m</kbd> to see mode information, which confirms that `Global-Visual-Line-Mode` is enabled.  Also, doing <kbd>C-h v</kbd> `fill-column` shows:
```
Its value is 103
Original value was 70
Local in buffer settings.org; global value is 70
```
Which seems to me to confirm that it "should" work (unless I am misunderstanding something)?

### Symptom 2: Emacs hanging, CPU near 100%

On the other hand, if I get it to actually work (to actually wrap lines), and then try to open another Emacs frame, Emacs hangs (becomes unresponsive).  If I open `htop` in a terminal I can see my Emacs command using near 100% CPU and then I need to kill it.

The following are the ways (as I recall) I was able to get it to "actually work."
- Add `(visual-fill-column-mode 1)` into `my-org-mode-setup` function which is called by `org-mode-hook` to set it up in each Orgmode buffer (this was before I tried doing it the global way, as discussed above).
- Calling <kbd>M-x</kbd> `visual-fill-column-mode` directly.

To be clear, there was no state I could seem to get into where the soft wrap worked as intended, without hanging my Emacs (upon spawning a new frame).  It was always either one or the other.

### More environment (emacsclient, emacs daemon)

In case it is relevant, I run Emacs in daemon mode as a systemd user service (`ExecStart=/usr/bin/emacs --fg-daemon`).  I then launch additional frames by way of a keybinding in i3 which executes `emacsclient -cne '(switch-to-buffer "*scratch*")'`.  To save you bothering to look them up, here is what those options mean:
```
-c, --create-frame      Create a new frame instead of trying to
                        use the current Emacs frame

-n, --no-wait           Don't wait for the server to return

-e, --eval              Evaluate the FILE arguments as ELisp expressions

```

Finally, in my init file, I have `(add-to-list 'default-frame-alist '(fullscreen . maximized))` which opens the new `emacsclient` frames by default `maximized` (which in the context of i3 just makes them fill whatever space that i3 gives them).

I mention all of this, because I remember reading echoes of similar things in other Issues I researched, before deciding to lodge this one.

### Next steps

I have tried to include all relevant information, however if there is anything else you are curious about, please do not hesitate to ask.  It would be wonderful to eventually get this working, I am very willing to do what I can from my end to assist.

I am sure I will continue troubleshooting on my end as time allows.

I guess the next thing for me will be to start with a vanilla Emacs (`emacs -q`) and then after that start bisecting my init, etc...

Until then, any feedback or pointers what to look for would be greatly appreciated.

Cheers!  :beers:

**Comment by joostkremers** [comment]
> ### Symptom 1: global-visual-line-mode not working
> 
> By not working, I mean that the mode seems to be enabled, it is just not doing anything (not wrapping any text). I enable it like so in my init file:

Are you talking about `global-visual-line-mode` or `global-visual-fill-column-mode`? The two are unrelated, except for the fact that the latter is useful if you use the former.

> ```
> (global-visual-line-mode 1)
> (setq-default visual-fill-column-width 103)
> ```

You don't activate `visual-fill-column-mode` here AFAICT, so the only effect you would see is that lines are wrapped at word boundaries rather than in the middle of words.

> I can go into buffer in question, and execute C-h m to see mode information, which confirms that `Global-Visual-Line-Mode` is enabled. Also, doing C-h v `fill-column` shows:
> 
> ```
> Its value is 103
> Original value was 70
> Local in buffer settings.org; global value is 70
> ```

That must be the result of some other setting in your init file, because `visual-fill-column-mode` doesn't change `fill-column`, not even buffer-locally.

> Which seems to me to confirm that it "should" work (unless I am misunderstanding something)?

This first problem may simply be a misunderstanding of how `visual-fill-column-mode` works and how it should be activated. If you wish to use it with `global-visual-line-mode`, you need to activate both in your init file:

```
(global-visual-line-mode)
(setq-default visual-fill-column-width 103)
(global-visual-fill-column-mode)
```

> The following are the ways (as I recall) I was able to get it to "actually work."
> 
> * Add `(visual-fill-column-mode 1)` into `my-org-mode-setup` function which is called by `org-mode-hook` to set it up in each Orgmode buffer (this was before I tried doing it the global way, as discussed above).
> 
> * Calling M-x `visual-fill-column-mode` directly.

Yes, that makes sense, because both those methods actually activate `visual-fill-column-mode`. Your snippet above does not. :wink:

[BTW, I rearranged your post a bit here...]

> ### Symptom 2: Emacs hanging, CPU near 100%
> 
> On the other hand, if I get it to actually work (to actually wrap lines), and then try to open another Emacs frame, Emacs hangs (becomes unresponsive). If I open `htop` in a terminal I can see my Emacs command using near 100% CPU and then I need to kill it.

My hunch is that that's not something `visual-fill-column-mode` can do much about. `visual-fill-column-mode` is actually pretty simple. All it does is widen the window margins, thus narrowing the text area. That's basically it. For some reason, the combination of your window manager, a maximized Emacs frame and wider than normal window margins triggers a bug, which may be in the window manager's code or in Emacs.

It's possible that `visual-fill-column-mode` does something that's normally triggered only once but for some reason in your particular setup is triggered over and over again (which may be related to the `split-window` window parameter). Personally, though, I have no problems using `visual-fill-column-mode` in a maximized frame, so I suspect `visual-fill-column-mode` itself is not to blame.

The best thing to see would be of course in what function Emacs gets stuck. But if you need to kill Emacs, that's probably difficult to figure out...

A couple of things I would try and test:

- Try without your personal config. The [emacs-sandbox.sh](https://github.com/alphapapa/emacs-sandbox.sh) comes in handy for that.
- Set the window margins manually (see `set-window-margins`) and see if that triggers the problem.
- Upgrade Emacs to version 27.1; you never know, the bug may already have been fixed.
- Try with a different (non-tiling) window manager (if you have XFCE installed, perhaps you can use that).

I really can't say more about this given your description of your issues. You'd need to do more testing in order to pinpoint the problem.

**Comment by TRSx80** [comment]
Thanks for the fast reply!

> Are you talking about `global-visual-line-mode` or `global-visual-fill-column-mode`? The two are unrelated, except for the fact that the latter is useful if you use the former.
> 
> > ```
> > (global-visual-line-mode 1)
> > (setq-default visual-fill-column-width 103)
> > ```
> 
> You don't activate `visual-fill-column-mode` here AFAICT, so the only effect you would see is that lines are wrapped at word boundaries rather than in the middle of words.

I'm sorry, I made a typo!  I think because the names are just so similar.  I actually *do* turn on both:

```
(global-visual-line-mode 1)
;; Soft wrap right side in any buffer where above will be turned
;; on.
(global-visual-fill-column-mode 1)
;; Above wraps slightly differently than hard wrap, so we adjust
;; the following slightly to achieve the same look.
(setq-default visual-fill-column-width 103)
```

I seem to make the same mistake below.  However, both `Global-Visual-Line-Mode` *and* `Global-Visual-Fill-Column` modes *are* actually turned on, regardless of what I incompletely state below:

> > I can go into buffer in question, and execute C-h m to see mode information, which confirms that `Global-Visual-Line-Mode` is enabled. Also, doing C-h v `fill-column` shows:
> > ```
> > Its value is 103
> > Original value was 70
> > Local in buffer settings.org; global value is 70
> > ```
> 
> That must be the result of some other setting in your init file, because `visual-fill-column-mode` doesn't change `fill-column`, not even buffer-locally.

This is an interesting tidbit.  It is possible this is some leftover from all my dickering around.  I was generally re-starting Emacs from scratch in between, but maybe not this last time.  Thanks for the tip.

> My hunch is that that's not something `visual-fill-column-mode` can do much about. `visual-fill-column-mode` is actually pretty simple. All it does is widen the window margins, thus narrowing the text area. That's basically it. For some reason, the combination of your window manager, a maximized Emacs frame and wider than normal window margins triggers a bug, which may be in the window manager's code or in Emacs.
> 
> It's possible that `visual-fill-column-mode` does something that's normally triggered only once but for some reason in your particular setup is triggered over and over again (which may be related to the `split-window` window parameter). Personally, though, I have no problems using `visual-fill-column-mode` in a maximized frame, so I suspect `visual-fill-column-mode` itself is not to blame.
> 
> The best thing to see would be of course in what function Emacs gets stuck. But if you need to kill Emacs, that's probably difficult to figure out...
> 
> A couple of things I would try and test:
> 
>     * Try without your personal config. The [emacs-sandbox.sh](https://github.com/alphapapa/emacs-sandbox.sh) comes in handy for that.
> 
>     * Set the window margins manually (see `set-window-margins`) and see if that triggers the problem.
> 
>     * Upgrade Emacs to version 27.1; you never know, the bug may already have been fixed.
> 
>     * Try with a different (non-tiling) window manager (if you have XFCE installed, perhaps you can use that).
> 
> 
> I really can't say more about this given your description of your issues. You'd need to do more testing in order to pinpoint the problem.

This is perfectly understandable.  You have given me some good ideas of more places to look, that I did not have before, so I appreciate that.  After I have had a chance to hack away some more on this, I will report back what I find.

Until then, enjoy your weekend!  Cheers!  :beers:

**Comment by joostkremers** [comment]
> I'm sorry, I made a typo! I think because the names are just so similar. I actually _do_ turn on both:


>     (global-visual-line-mode 1)
>     ;; Soft wrap right side in any buffer where above will be turned
>     ;; on.
>     (global-visual-fill-column-mode 1)
>     ;; Above wraps slightly differently than hard wrap, so we adjust
>     ;; the following slightly to achieve the same look.
>     (setq-default visual-fill-column-width 103)


I cannot explain this... I tested with `emacs-sandbox.sh` myself and I seem to get the same behaviour. For some reason, `visual-fill-column-mode` isn't activated even though `visual-line-mode` is active. At least it's not reliably activated, but I haven't been able to find out under what conditions it works or doesn't work...

**Comment by joostkremers** [comment]
> I cannot explain this... I tested with `emacs-sandbox.sh` myself and I seem to get the same behaviour. For some reason, `visual-fill-column-mode` isn't activated even though `visual-line-mode` is active. At least it's not reliably activated, but I haven't been able to find out under what conditions it works or doesn't work...

My hunch is that the way `visual-fill-column-mode` is turned on in the global variant is actually wrong. I wanted it to be dependent on `visual-line-mode`, i.e., that `v-f-c-mode` is only turned on when `v-l-mode` is active as well. But that requires that `v-l-mode` is activated before `v-f-c-mode`, and with globalized minor modes there's no way to guarantee that.

So I guess the way to solve that issue is to activate `v-f-c-mode` unconditionally. (Well, it's still only activated in buffers that visit a file.) Since `global-visual-line-mode` turns on `visual-line-mode` in every buffer, that's probably not an issue. I just pushed a fix that implements this, so hopefully the first part of your problem is gone.

As for the second part, I really have no idea. Since I don't have the time right now to figure out a way to replicate your setup (Emacs 26, i3-gap) I can't really debug it. If you learn anything new, feel free to post it here, perhaps it'll give me some ideas.

**Comment by joostkremers** [comment]
I'm closing this issue, because I'm moving the repo to Codeberg.org. If the problem crops up again, feel free to create an issue at https://codeberg.org/joostkremers/visual-fill-column.
