### ISSUE TITLE
Highlight for beginning of wrapped line error if the character is a Chinese

### ISSUE THREAD

**Issue by zw963** [joostkremers/visual-fill-column#46]
Please see following screenshot.

![image](https://user-images.githubusercontent.com/549126/97716870-1c607c00-1aff-11eb-8beb-37b91e5fd28e.png)

**Comment by joostkremers** [comment]
I'm afraid I'm not sure what exactly you mean. Could you elaborate a bit more? What do you expect to see, can you confirm the problem  with `emacs -Q` and just `visual-fill-column` installed?

**Comment by zw963** [comment]
![image](https://user-images.githubusercontent.com/549126/97828358-db848500-1d01-11eb-9a0c-05e38fb7dfd3.png)

Above is two line comment:

first is:

```el
;; 让 helm 弹出的窗口, 总在最下面, 当开启 follow-mode 时, 这个和 neotree not 不工作.
```
second:

```el
;; 让 helm 弹出的窗口, 总在最下面, 当开启 follow-mode 时, 这个和 neotree not  work 不工作.
```

Please check the highlight in the first sample,  `不工作` should use comment font-lock as
`work 不工作` does.

**Comment by joostkremers** [comment]
Thanks, I see now what you mean. Unfortunately, I cannot reproduce it with `emacs -Q`:

![Screenshot from 2020-11-02 10-25-16](https://user-images.githubusercontent.com/191630/97851507-bb4ec900-1cf5-11eb-8dd7-0aae84b44470.png)

As you can see at the bottom of the screen shot, the face seems to be as expected.

Could you check with `C-u C-x =` to see what text properties are on the text `不工作` in the first example? That might help pin down the problem.

Have you tried what happens without `visual-fill-column-mode`, if you make the window small enough? `visual-fill-column` doesn't do anything with faces or font lock, so I wouldn't be surprised if this bug is somewhere else.

**Comment by zw963** [comment]
> Could you check with C-u C-x = to see what text properties are on the text 不工作 in the first example? 

Yes, we are same.

i can confirm, this issue happen only on one of following mode is enabled.

```el
(global-hl-line-mode t)
(global-display-fill-column-indicator-mode t)
```

when i make window small enough, i can see the line which start with Chinese, have wrong fontlock color.

![image](https://user-images.githubusercontent.com/549126/98206121-5b198a80-1f74-11eb-89b4-ec54bad2e67e.png)

I will closing this issue, thank you.
