### ISSUE TITLE
Visual-fill-column overrides custom left-margin

### ISSUE THREAD

**Issue by arozbiz** [joostkremers/visual-fill-column#48]
I use `(setq-default left-margin-width 1 right-margin-width 0)` to give myself a small left margin (I don't use line numbers). But visual-fill-column overrides that margin. Is this intended behavior? Is there a workaround? Thanks.

**Comment by joostkremers** [comment]
> I use `(setq-default left-margin-width 1 right-margin-width 0)` to give myself a small left margin (I don't use line numbers). But visual-fill-column overrides that margin.

Yes, true.

> Is this intended behavior?

More of a decision by omission... It's not a use-case I ever considered.

> Is there a workaround? Thanks.

Currently, no, I don't think so. I could add a user option to add some space to the margins, or I could check the margins at the moment `visual-fill-column-mode` is activated and keep those values as minimum values. I'd have to think a bit about which option would be better.

**Comment by joostkremers** [comment]
>  I could add a user option to add some space to the margins, or I could check the margins at the moment `visual-fill-column-mode` is activated and keep those values as minimum values.

Well, I tried to implement the second option, albeit for a different purpose, but it doesn't seem to work (See issue #49), so that's not an option.

There is, however, a new user option, `visual-fill-column-extra-text-width`, implemented in response to an [issue](https://github.com/joostkremers/writeroom-mode/issues/66) with `writeroom-mode`, which you may be able to use. It's actually meant to add extra space to the text area, but if you provide it with a negative number, it should add some space to the margin. So try adding the following to your init file (or use `M-x customize-option RET visual-fill-column-extra-text-width RET`):

    (setq visual-fill-column-extra-text-width '(-1 . 0))

That should give you a one-character left margin.
