### ISSUE TITLE
 visual-fill-column-mode prevents git-gutter to show up

### ISSUE THREAD

**Issue by farynaio** [joostkremers/visual-fill-column#50]
I found that when  visual-fill-column-mode is active gutter from the git-gutter-mode don't show up.

Is there any way to work around this?

**Comment by joostkremers** [comment]
`visual-fill-column-mode` uses the margins to narrow the text area, which means its next to impossible to make it compatible with other packages that use the margins, such as `git-gutter`. The only work-around here is to use an alternative to `git-gutter` that uses the fringes instead of the margins. I know of two options: `git-gutter-fringe` (by the same author as `git-gutter`) and `diff-hl`, which I use myself.

**Comment by farynaio** [comment]
@joostkremers thanks, the `diff-hl` is pretty awesome but I found this functionality is already in Magit. The git-gutter-fringe in preview looks exactly like git-gutter for me :)

I decided to stop using visual-fill-column for the moment. Opening another window next to the main one solves my problem with too wide screen.
